name: run automate_newsletter.py

on:
  schedule:
    - cron: '39 3 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9.x' # install the python version needed
          
      - name: install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libpango1.0-dev libpangocairo-1.0-0 libcairo2-dev pkg-config

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          # Create a temporary requirements file without problematic packages
          grep -v "pyobjc\|manim\|contourpy\|hdbscan\|isosurfaces" requirements.txt > requirements_linux.txt
          # Install core dependencies first
          pip install "numpy>=2.0.0" "pandas>=2.0.0" "scipy>=1.10.0"
          # Install the rest of the requirements
          pip install -r requirements_linux.txt
          
      - name: execute py script
        env:
          NEWSLETTER_EMAIL: ${{ secrets.NEWSLETTER_EMAIL }}
          NEWSLETTER_PASSWORD: ${{ secrets.NEWSLETTER_PASSWORD }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
          GOOGLE_SHEET_ID_UNSUB: ${{ secrets.GOOGLE_SHEET_ID_UNSUB }}
          GOOGLE_SHEET_API_KEY: ${{ secrets.GOOGLE_SHEET_API_KEY }}
          private_key_id: ${{ secrets.private_key_id }}
          private_key: ${{ secrets.private_key }}
        run: python src/scripts/automate_newsletter.py
          
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "daily morning scheduled newsletter generation / send" --allow-empty)
          
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main 