name: test_requirements

on:
  push:
    branches: ["main"]  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9.x' # install the python version needed
          
      - name: install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libpango1.0-dev libpangocairo-1.0-0 libcairo2-dev pkg-config

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute py script with test flag
        env:
          NEWSLETTER_EMAIL: ${{ secrets.NEWSLETTER_EMAIL }}
          NEWSLETTER_PASSWORD: ${{ secrets.NEWSLETTER_PASSWORD }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
          GOOGLE_SHEET_ID_UNSUB: ${{ secrets.GOOGLE_SHEET_ID_UNSUB }}
          GOOGLE_SHEET_API_KEY: ${{ secrets.GOOGLE_SHEET_API_KEY }}
          private_key_id: ${{ secrets.private_key_id }}
          private_key: ${{ secrets.private_key }}
        run: python src/scripts/automate_newsletter.py --test 