name: test_container

on:
  push:
    branches: ["main"]  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9.x' # install the python version needed

      - name: execute py script with test flag
        run: python test_container.py